Scan for all markdown files in repo Run on local markdown regardless of wiki pages Set exit code on demand

diff --git a/.github/workflows/non-shall-pass.yml b/.github/workflows/non-shall-pass.yml
--- a/.github/workflows/non-shall-pass.yml
+++ b/.github/workflows/non-shall-pass.yml
@@ -1,6 +1,6 @@
 # This workflow will run validations against all hyperlinks in markdown files (include Wiki pages)
 
-name: markdown-hyperlink-auditor
+name: none-shall-pass
 
 # Controls when the workflow will run
 on:
@@ -12,23 +12,20 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - name: Python
-        uses: actions/setup-python@v2
+      - uses: actions/setup-python@v2
         with:
           python-version: '3.x'
+      - name: Variants
+        run: |
+          echo "FAILED=0" >> $GITHUB_ENV
+          echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
+          echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
       - name: Dependents
         run: |
           python -m pip install --upgrade pip
-          echo "FAILED=0" >> $GITHUB_ENV
           curl -O https://raw.githubusercontent.com/thevickypedia/none-shall-pass/main/src/validator.py
-          echo "REPO=${{ github.event.repository.name }}" >> $GITHUB_ENV
-          echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
       - name: Validator
-        run: |
-          echo "Exit Code: ${{ env.FAILED }}"
-          python validator.py
+        run: python validator.py
       - name: Checker
         if: ${{ env.FAILED != '0' }}
-        run: |
-          echo "Non zero exit code: ${{ env.FAILED }}"
-          exit 1
+        run: exit 1
